version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - ja-server
    ports:
      - "5432:5432"

  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    networks: 
      - ja-server
    volumes: 
      - "activemq-conf:/opt/activemq/conf"
      - "activemq-data:/data/activemq"
      - "activemq-log:/var/log/activemq"
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048
  fakes3: 
    image: lphoward/fake-s3:latest 
    ports:
      - "4569:4569"
    volumes: 
      - fakes3-data:/fakes3_root
    networks: 
      - ja-server

  minio: 
    image: minio/minio
    ports:
      - "3000:9000"
      - "9000:9000"
    volumes: 
      - minio-data:/data
    networks: 
      - ja-server
    command: ["server", "/data"]

  redis: 
    image: redis
    ports:
      - "6379:6379"
    networks: 
      - ja-server
volumes:
  postgresql-data: # named volumes can be managed easier using docker-compose
  activemq-conf:
  activemq-data:
  activemq-log:
  fakes3-data:
  minio-data:

networks:
  ja-server: